import type { Metadata } from 'next';
import { SCHOOL } from '@/lib/config';
// Self-hosted ad fonts. Imported at the root so the print routes get the exact
// same faces the parent's preview used. Generated by scripts/fetch-fonts.mjs.
import './fonts.css';
import './globals.css';

export const metadata: Metadata = {
  title: {
    default: `${SCHOOL.program} Program Ads`,
    template: `%s · ${SCHOOL.program}`,
  },
  description: `Reserve a congratulations ad in the ${SCHOOL.season} ${SCHOOL.program} program book.`,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
